<?php 

CREATE TABLE users_info (id INT NOT NULL AUTO_INCREMENT , name VARCHAR(100) NOT NULL , u_name VARCHAR(100) NOT NULL , email VARCHAR(100) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL , password VARCHAR(100) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL , created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP , PRIMARY KEY (id));



?>